package database

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/pressly/goose/v3"

	"video_share/migrations"
)

// Migrator 通过 goose 的 Provider API 应用版本化的 SQL 迁移，该 API 会显式
// 固定数据库方言。旧版的包级 goose API 默认使用 PostgreSQL 方言，并会为其
// 版本表生成 Postgres DDL（GENERATED BY DEFAULT AS IDENTITY），这会导致
// 第一次 MySQL 迁移失败。使用带 DialectMySQL 的 Provider 可以让
// up/down/status 保持在同一方言下，并将错误显式抛出，而不是打印到全局日志。
type Migrator struct {
	provider *goose.Provider
}

// NewMigrator 创建一个从内嵌文件系统读取迁移、并使用 MySQL 方言的 Migrator。
func NewMigrator(db *sql.DB) (*Migrator, error) {
	provider, err := goose.NewProvider(goose.DialectMySQL, db, migrations.FS)
	if err != nil {
		return nil, fmt.Errorf("new goose provider: %w", err)
	}
	return &Migrator{provider: provider}, nil
}

// Up 应用所有待执行的迁移并返回已应用的结果。返回 nil 且无错误表示没有需要
// 应用的迁移。
func (m *Migrator) Up(ctx context.Context) ([]*goose.MigrationResult, error) {
	results, err := m.provider.Up(ctx)
	if err != nil {
		return nil, fmt.Errorf("migrate up: %w", err)
	}
	return results, nil
}

// Down 回滚最近一次已应用的迁移。
func (m *Migrator) Down(ctx context.Context) (*goose.MigrationResult, error) {
	result, err := m.provider.Down(ctx)
	if err != nil {
		return nil, fmt.Errorf("migrate down: %w", err)
	}
	return result, nil
}

// Status 按版本顺序返回所有已知迁移的状态。
func (m *Migrator) Status(ctx context.Context) ([]*goose.MigrationStatus, error) {
	statuses, err := m.provider.Status(ctx)
	if err != nil {
		return nil, fmt.Errorf("migrate status: %w", err)
	}
	return statuses, nil
}
